# Generated by Django 3.2 on 2023-05-07 04:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Memorialmatrix', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('inquiry', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=100)),
                ('message', models.TextField(max_length=4096)),
                ('is_read', models.BooleanField(default=False)),
                ('notes', models.CharField(blank=True, max_length=250, null=True)),
                ('message_received_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='WebsiteConfigParameter',
            fields=[
                ('parameter_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('parameter_value', models.TextField()),
                ('parameter_description', models.TextField(default='')),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='history_admin',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': ' History_Admin', 'verbose_name_plural': 'historical Admins'},
        ),
        migrations.AlterModelOptions(
            name='history_location',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': ' History_Location', 'verbose_name_plural': 'historical locations'},
        ),
        migrations.AlterModelOptions(
            name='history_medialinks',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': ' History_MediaLink', 'verbose_name_plural': 'historical MediaLinks'},
        ),
        migrations.AlterModelOptions(
            name='history_memorial',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': ' History_Memorial', 'verbose_name_plural': 'historical memorials'},
        ),
        migrations.AlterModelOptions(
            name='history_webuser',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': ' History_WebUser', 'verbose_name_plural': 'historical web users'},
        ),
        migrations.RemoveField(
            model_name='history_memorial',
            name='mem_organization',
        ),
        migrations.RemoveField(
            model_name='memorial',
            name='mem_organization',
        ),
        migrations.AddField(
            model_name='history_memorial',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='history_memorial',
            name='memorial_day_observance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='history_webuser',
            name='web_user_affiliated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='memorial',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='memorial',
            name='memorial_day_observance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='webuser',
            name='web_user_affiliated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='history_admin',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='history_admin',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='history_location',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='history_medialinks',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='history_memorial',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='history_webuser',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.DeleteModel(
            name='History_Organization',
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
    ]
