import '../e2e/Admin_Scripts/Admin_Add_Edit_Delete_Admin.cy'
import '../e2e/Admin_Scripts/Admin_Add_Edit_Delete_Contact.cy'
import '../e2e/Admin_Scripts/Admin_Report_Add.cy'
import '../e2e/Admin_Scripts/Admin_REST_api_submit.cy'
// import '../e2e/Admin_Scripts/Admin_Wagtail_Add_Edit_Delete.cy'