# Generated by Django 3.2 on 2022-12-07 18:22

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0078_referenceindex'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('pageTitle', models.CharField(max_length=250)),
                ('body', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='FooterPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('generalEmail', models.CharField(blank=True, max_length=250)),
                ('pressEmail', models.CharField(blank=True, max_length=250)),
                ('hashTag', models.CharField(blank=True, max_length=250)),
                ('donate', models.CharField(blank=True, max_length=250)),
                ('facebookLink', models.CharField(blank=True, max_length=250)),
                ('emailLink', models.CharField(blank=True, max_length=250)),
                ('instagramLink', models.CharField(blank=True, max_length=250)),
                ('twitterLink', models.CharField(blank=True, max_length=250)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
