# Generated by Django 3.2 on 2023-05-07 04:27

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0083_workflowcontenttype'),
        ('WagtailApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaqPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('questions', wagtail.fields.StreamField([('faq_question', wagtail.blocks.StructBlock([('question', wagtail.blocks.CharBlock(max_length=255)), ('answer', wagtail.blocks.RichTextBlock())]))], default=[], use_json_field=None)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='SponsorPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('sponsors', wagtail.fields.StreamField([('sponsor', wagtail.blocks.StructBlock([('sponsorName', wagtail.blocks.CharBlock(max_length=255)), ('sponsorDescription', wagtail.blocks.RichTextBlock()), ('photoUrl', wagtail.blocks.URLBlock(max_length=2048, required=False))]))], default=[], use_json_field=None)),
                ('advisors', wagtail.fields.StreamField([('advisors', wagtail.blocks.StructBlock([('advisorName', wagtail.blocks.CharBlock(max_length=255)), ('advisorDescription', wagtail.blocks.RichTextBlock()), ('advisorPhotoUrl', wagtail.blocks.URLBlock(max_length=2048, required=False))]))], default=[], use_json_field=None)),
                ('volunteers', wagtail.fields.StreamField([('volunteers', wagtail.blocks.StructBlock([('volunteerName', wagtail.blocks.CharBlock(max_length=255)), ('volunteerDescription', wagtail.blocks.RichTextBlock()), ('volunteerPhotoUrl', wagtail.blocks.URLBlock(max_length=2048, required=False))]))], default=[], use_json_field=None)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.RemoveField(
            model_name='footerpage',
            name='emailLink',
        ),
        migrations.RemoveField(
            model_name='footerpage',
            name='generalEmail',
        ),
        migrations.RemoveField(
            model_name='footerpage',
            name='hashTag',
        ),
        migrations.RemoveField(
            model_name='footerpage',
            name='pressEmail',
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='coreStaffTitle',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='coreStaffs',
            field=wagtail.fields.StreamField([('coreStaffs', wagtail.blocks.StructBlock([('staffName', wagtail.blocks.CharBlock(max_length=255)), ('staffDescription', wagtail.blocks.RichTextBlock()), ('photoUrl', wagtail.blocks.URLBlock(max_length=2048, required=False))]))], default=[], use_json_field=None),
        ),
        migrations.AddField(
            model_name='footerpage',
            name='shareStoryLink',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
